# Generated by Django 3.2.25 on 2026-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('cod', 'Cash on Delivery')], default='Cash on Delivery', max_length=50),
        ),
    ]
